stages:
  - init
  - build
  - test
  - cleanup

################################################################################
# Job templates
################################################################################

.base:
  variables:
    GITLAB_SITE: "OLCF GitLab"
    EXTERNAL_WORKDIR: /gpfs/wolf/proj-shared/csc337/veloc/ci/${CI_PIPELINE_ID}_${CI_BUILD_LABEL}
#    EXTERNAL_WORKDIR: /usr/workspace/kosinov/veloc/ci/${CI_PIPELINE_ID}_${CI_BUILD_LABEL}
#    CI_REPOSITORY_URL1: ssh://git@czgitlab.llnl.gov:7999/ecp-veloc/VELOC.git
  before_script:
    - mkdir -pv ${EXTERNAL_WORKDIR}/source
    - cd ${EXTERNAL_WORKDIR}/source
    - module purge
    - module load ${COMPILER} cmake git python/3.7.0 spectrum-mpi boost
    - export CC=${CC_VAR} CXX=${CXX_VAR} FC=${FC_VAR}

# Use a work directory on the shared filesystem accessible to compute nodes
.init-step:
  extends:
    - .base
  stage: init
  tags: [nobatch]
  script:
    - cd ..
    - rm -rfv source
    - echo $EXTERNAL_WORKDIR
    - echo $CI_REPOSITORY_URL
    - git clone -b ${CI_COMMIT_BRANCH} --depth=1  ${CI_REPOSITORY_URL} source

.build-step:
  extends:
    - .base
  stage: build
  tags: [nobatch]
  script:
    - pip3 install --user wget bs4
    - mkdir -p $PWD/../deploy
#    - ./auto-install.py --without-boost $PWD/../deploy
    - ./auto-install.py --protocol socket_queue $PWD/../deploy

.test-step:
  extends:
    - .base
  stage: test
  script:
    - echo $LD_LIBRARY_PATH
    - cd build
    - ctest -VV
  tags: [batch]

.cleanup-step:
  extends:
    - .base
  stage: cleanup
  tags: [nobatch]
  script:
    - cd ${CI_PROJECT_DIR}
    - rm -rf ${EXTERNAL_WORKDIR}


################################################################################
# XL + SMPI
################################################################################
.ascent-xl-smpi:
  variables:
    CI_BUILD_LABEL: ascent-xl-smpi
    COMPILER: xl/16.1.1-7

ascent-xl-smpi-init:
  extends:
    - .ascent-xl-smpi
    - .init-step

ascent-xl-smpi-build:
  variables:
#    COMPILER: xl/2020.08.24
    CC_VAR: xlc 
    CXX_VAR: xlc++ 
    FC_VAR: xlf
  extends:
    - .ascent-xl-smpi
    - .build-step

ascent-xl-smpi-test:
  extends:
    - .ascent-xl-smpi
    - .test-step
  tags:
    - batch
  variables:
    SCHEDULER_PARAMETERS: "-P CSC337 -W 1:00 -nnodes 2"

ascent-xl-smpi-cleanup:
  extends:
    - .ascent-xl-smpi
    - .cleanup-step

################################################################################
# GCC + SMPI
################################################################################
.ascent-gcc-smpi:
  variables:
    CI_BUILD_LABEL: ascent-gcc-smpi
    COMPILER: gcc/8.1.1

ascent-gcc-smpi-init:
  extends:
    - .ascent-gcc-smpi
    - .init-step

ascent-gcc-smpi-build:
  variables:
    CC_VAR: gcc 
    CXX_VAR: g++ 
    FC_VAR: gfortran 
  extends:
    - .ascent-gcc-smpi
    - .build-step

ascent-gcc-smpi-test:
  extends:
    - .ascent-gcc-smpi
    - .test-step
  tags:
    - batch
  variables:
#    LSF_SCHEDULER_PARAMETERS: "-P CSC337 -W 1:00 -nnodes 2"
    SCHEDULER_PARAMETERS: "-P CSC337 -W 1:00 -nnodes 2"

ascent-gcc-smpi-cleanup:
  extends:
    - .ascent-gcc-smpi
    - .cleanup-step
