slurm-job:
  tags:
    - quartz
    - batch
  variables:
     LLNL_SLURM_SCHEDULER_PARAMETERS: "-N 4 -p pbatch"
     PERSISTENT: "/g/g19/kosinov/persistent"
     SCRATCH: "/tmp/scratch"
  script:
    - cp test/CMakeLists_slurm.txt test/CMakeLists.txt
    - cp test/test_cleanup_slurm.sh test/test_cleanup.sh
    - cp test/test_simulate_multilevel_corruption_slurm.sh test/test_simulate_multilevel_corruption.sh
    - if [ -d ../deploy ]; then rm -R ../deploy; fi
    - mkdir ../deploy
    - ml cmake/3.18
    - ml gcc/8.1
    - ml boost/1.72.0
    - ./auto-install.py --without-boost $PWD/../deploy
    - cd build
    - ctest -VV
lsf-job:
  tags:
    - lassen
    - batch
  variables:
     LLNL_LSF_SCHEDULER_PARAMETERS: "-nnodes 4 -q pbatch"
     PERSISTENT: "/g/g19/kosinov/persistent"
     SCRATCH: "/dev/shm/scratch"
  script:
    - cp test/CMakeLists_lsf.txt test/CMakeLists.txt
    - cp test/test_cleanup_lsf.sh test/test_cleanup.sh
    - cp test/test_simulate_multilevel_corruption_lsf.sh test/test_simulate_multilevel_corruption.sh
    - ml cmake/3.18
    - ml gcc/8.3
    - ml boost
    - if [ -d ../deploy ]; then rm -R ../deploy; fi
    - mkdir ../deploy
    - ./auto-install.py --without-boost $PWD/../deploy
    - cd build
    - ctest -VV

