language: c++

before_install:
- sudo apt-get update
- sudo apt-get install -y libopenmpi-dev openmpi-bin zlib1g-dev

script:
- rm -rf $HOME/deploy
- ./bootstrap.sh
- mkdir -p $HOME/deploy
- ./auto-install.py $HOME/deploy
- ctest --verbose

branches:
    only:
    - master
    - barebone