#!/bin/bash

INSTALL_PREFIX=$HOME/deploy
export CMAKE_PREFIX_PATH=$INSTALL_PREFIX/share/cmake
cmake -DCOMM_QUEUE=socket_queue -DPOSIX_IO=rw -DWITH_AXL_PREFIX=$INSTALL_PREFIX -DWITH_ER_PREFIX=$INSTALL_PREFIX -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX $1
