#!/bin/bash
set -x

# note: no need for config.fti (use SCR config instead)
# left the arg there for now

# flush every 10th checkpoint
export SCR_FLUSH=10

#totalview srun -a -n4 -N4 ./hd.exe 4 config.fti
#srun -n4 -N4 ./hd.exe 4 config.fti

totalview srun -a -n4 -N4 ./hd_veloc.exe 4 config.fti
#srun -n4 -N4 ./hd_veloc.exe 4 config.fti
