#!/bin/bash
set -x

# note: no need for config.fti (use SCR config instead)
# left the arg there for now

# enable some debug messages
export SCR_DEBUG=1

# number of seconds between checkpoints
export SCR_CHECKPOINT_SECONDS=5

# flush every 10th checkpoint
export SCR_FLUSH=3

#totalview srun -a -n4 -N4 ./heatdis_mem 4 config.fti
#srun -n4 -N4 ./heatdis_mem 4 config.fti

#totalview srun -a -n4 -N4 ./heatdis_file 4 config.fti
#srun -n4 -N4 ./heatdis_file 4 config.fti

#mpirun -np 4 ./heatdis_memfile 4 config.fti
srun -n4 -N4 ./heatdis_memfile 4 config.fti
#totalview srun -a -n4 -N4 ./heatdis_memfile 4 config.fti
#srun -n4 -N4 ./heatdis_memfile 4 config.fti
