# - Try to find RANKSTR
# Once done this will define
#  RANKSTR_FOUND - System has libRankstr
#  RANKSTR_INCLUDE_DIRS - The libRankstr include directories
#  RANKSTR_LIBRARIES - The libraries needed to use libRankstr

FIND_PATH(WITH_RANKSTR_PREFIX
    NAMES include/er.h
)

FIND_LIBRARY(RANKSTR_LIB NAMES rankstr HINTS ${WITH_RANKSTR_PREFIX}/lib)

LIST(APPEND RANKSTR_LIBRARIES ${RANKSTR_LIB} ${RANKSTR_LIB})

FIND_PATH(RANKSTR_INCLUDE_DIRS
    NAMES rankstr_mpi.h
    HINTS ${WITH_RANKSTR_PREFIX}/include
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RANKSTR DEFAULT_MSG
    RANKSTR_LIBRARIES
    RANKSTR_INCLUDE_DIRS
)

# Hide these vars from ccmake GUI
MARK_AS_ADVANCED(
    RANKSTR_LIBRARIES
    RANKSTR_INCLUDE_DIRS
)
